export const Data = [
  {
    author: "John Doe",
    authorImage: "https://randomuser.me/api/portraits/men/11.jpg",
    content: "Just got back from my vacation, the beach was amazing!",
    image: "https://picsum.photos/300/200?random=1",
    video: null,
    createdAt: "2025-09-01T09:15:23Z",
  },
  {
    author: "Sarah Lee",
    authorImage: "https://randomuser.me/api/portraits/women/21.jpg",
    content: "Check out this cool dance clip I recorded yesterday!",
    image: null,
    video:
      "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
    createdAt: "2025-09-01T12:42:10Z",
  },
  {
    author: "Michael Brown",
    authorImage: "https://randomuser.me/api/portraits/men/31.jpg",
    content: "Morning coffee vibes ☕",
    image: "https://picsum.photos/300/200?random=2",
    video: null,
    createdAt: "2025-09-02T07:30:55Z",
  },
  {
    author: "Emily Carter",
    authorImage: "https://randomuser.me/api/portraits/women/41.jpg",
    content: "Today’s weather is perfect for a walk in the park.",
    image: null,
    video: null,
    createdAt: "2025-09-02T10:05:12Z",
  },
  {
    author: "David Wilson",
    authorImage: "https://randomuser.me/api/portraits/men/51.jpg",
    content: "New painting I just finished 🎨 What do you think?",
    image: "https://picsum.photos/300/200?random=3",
    video: null,
    createdAt: "2025-09-03T15:22:40Z",
  },
  {
    author: "Sophia Martinez",
    authorImage: "https://randomuser.me/api/portraits/women/61.jpg",
    content: "Started learning guitar this week 🎸 Excited for the journey!",
    image: null,
    video: null,
    createdAt: "2025-09-03T19:45:03Z",
  },
  {
    author: "Chris Johnson",
    authorImage: "https://randomuser.me/api/portraits/men/71.jpg",
    content: "Hiking trip was amazing! Nature is so refreshing 🍃",
    image: "https://picsum.photos/300/200?random=4",
    video: null,
    createdAt: "2025-09-04T08:11:17Z",
  },
  {
    author: "Linda Park",
    authorImage: "https://randomuser.me/api/portraits/women/81.jpg",
    content: "Here’s a short cooking tutorial I filmed today 👩‍🍳",
    image: null,
    video:
      "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_2mb.mp4",
    createdAt: "2025-09-04T13:59:45Z",
  },
  {
    author: "Robert King",
    authorImage: "https://randomuser.me/api/portraits/men/91.jpg",
    content: "Game night with friends 🎮 Who else loves retro games?",
    image: "https://picsum.photos/300/200?random=5",
    video: null,
    createdAt: "2025-09-05T20:30:09Z",
  },
  {
    author: "Olivia Davis",
    authorImage: "https://randomuser.me/api/portraits/women/12.jpg",
    content: "Weekend getaway photos 📸 Can’t wait to go back!",
    image: "https://picsum.photos/300/200?random=6",
    video: null,
    createdAt: "2025-09-06T11:24:33Z",
  },
  {
    author: "Daniel Green",
    authorImage: "https://randomuser.me/api/portraits/men/13.jpg",
    content: "Quick workout session 💪 Staying consistent!",
    image: null,
    video: null,
    createdAt: "2025-09-07T06:40:51Z",
  },
  {
    author: "Emma White",
    authorImage: "https://randomuser.me/api/portraits/women/14.jpg",
    content: "Trying out some new photography techniques 📷",
    image: "https://picsum.photos/300/200?random=7",
    video: null,
    createdAt: "2025-09-07T18:05:29Z",
  },
]
